apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-workflows
  repo: https://charts.akuity.io
  includeCRDs: true
  namespace: argo
  valuesFile: values.yaml

patches:
  - path: patch-argo-server.yaml
    target:
      version: v1
      kind: Deployment
      name: argo-server