apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- events.yaml
- minio.yaml
- workflows.yaml

patches:
  - path: patch-argo-application.yaml
    target:
      version: v1alpha1
      kind: Application