- op: replace
  path: "/spec/source/targetRevision"
  value: "HEAD"
# - op: replace
#   path: "/spec/destination/namespace"
#   value: "argocd"
- op: replace
  path: "/spec/destination/name"
  value: "{{server}}"
