- op: replace
  path: "/spec/source/targetRevision"
  value: "morey-tech-testing-1"
# - op: replace
#   path: "/spec/destination/namespace"
#   value: "argocd"
- op: replace
  path: "/spec/destination/name"
  value: "kind"