apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
spec:
  project: default
  source:
    repoURL: 'https://github.com/dhpup/workflows-events-demo'
    path: workflows
    targetRevision: HEAD
  destination:
    namespace: argo
    name: kind
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
