apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: minio
  releaseName: minio
  repo: https://charts.min.io/
  includeCRDs: true
  namespace: minio
  valuesFile: values.yaml