apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-events
  repo: https://charts.akuity.io
  includeCRDs: true
  namespace: argo-events
  valuesFile: values.yaml