## Argo Events configuration
## Ref: https://github.com/argoproj/argo-events

global:
    image:
        # -- If defined, a repository applied to all argo events deployments
        repository: quay.io/argoproj/argo-events
        # -- If defined, a tag applied to all argo events deployments
        tag: v1.6.3
        # -- If defined, an image pull policy will be applied to all argo events deployments
        pullPolicy: # IfNotPresent

# -- Installs necessary ClusterRoles to allow Argo Events to deploy to the same cluster Argo Events is installed in
clusterRoles:
    enabled: true

# -- Argo Event Bus configuration
eventbusController:
    replicas: 1

    image:
        repository: # defaults to global.image.repository
        tag: # defaults to global.image.tag
        pullPolicy: # IfNotPresent

    # -- Additional command line arguments to pass
    extraArgs:
    # - --loglevel
    # - debug

    natsStreamingImage:
        repository: nats-streaming # defaults to global.image.repository
        tag: "0.22.1" # defaults to global.image.tag

    natsMetricsExporterImage:
        repository: natsio/prometheus-nats-exporter # defaults to global.image.repository
        tag: "0.8.0" # defaults to global.image.tag

    resources:
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 50m
        #   memory: 64Mi

# -- Argo Event Source configuration
eventsourceController:
    replicas: 1

    image:
        repository: # defaults to global.image.repository
        tag: # defaults to global.image.tag
        pullPolicy: # IfNotPresent

    eventsourceImage:
        repository: # defaults to global.image.repository
        tag: # defaults to global.image.tag

    # -- Additional command line arguments to pass
    extraArgs:
    # - --loglevel
    # - debug

    resources:
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 50m
        #   memory: 64Mi

# -- Argo Sensor configuration
sensorController:
    replicas: 1

    image:
        repository: # defaults to global.image.repository
        tag: # defaults to global.image.tag
        pullPolicy: # IfNotPresent

    sensorImage:
        repository: # defaults to global.image.repository
        tag: # defaults to global.image.tag

    # -- Additional command line arguments to pass
    extraArgs:
    # - --loglevel
    # - debug

    resources:
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 50m
        #   memory: 64Mi

